"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-grpei%+nla48sx9hj6_b0eo+58b1tm=hrpem*e@fpv**tm&_%3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # Your Vite development server
    "http://127.0.0.1:5173", # Standard local host address
    "http://localhost:5174", # Alternate Vite port
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'market',
    'rest_framework',
    'drf_yasg',
    'django_celery_results',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://nexusrate_user:strong_secret_password@localhost:5432/nexusrate_db',
        conn_max_age=600
    )
}

# Vercel specific: Check for POSTGRES_URL if DATABASE_URL isn't set/working or just to be safe
if 'POSTGRES_URL' in os.environ:
    DATABASES['default'] = dj_database_url.parse(os.environ.get('POSTGRES_URL'))


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
# --------------------------------------------------------------------------
# CELERY SETTINGS (Using PostgreSQL as Broker)
# --------------------------------------------------------------------------

# IMPORTANT: You MUST use the credentials defined in your DATABASES dictionary.
# The format is: sqla+postgresql://USER:PASSWORD@HOST:PORT/NAME
CELERY_BROKER_URL = 'sqla+postgresql://nexusrate_user:strong_secret_password@localhost:5432/nexusrate_db'

# You can still use the database itself to store results (backend)
CELERY_RESULT_BACKEND = 'django-db' # Use Django's built-in ORM backend

# --------------------------------------------------------------------------
# CELERY BEAT (PERIODIC SCHEDULER) SETTINGS
# --------------------------------------------------------------------------

CELERY_BEAT_SCHEDULE = {
    'fetch-market-data-every-5-minutes': {
        'task': 'market.tasks.fetch_and_calculate_market_data', 
        
        # Runs every 5 minutes (a reasonable frequency for free tiers)
        'schedule': 300.0,
        
        'args': (), 
    },
}
